// ============================================================
// Águila Inventario Pro - Netlify Function: generate-phrase.js
// Backend Serverless para Generación de Frases con IA (Groq/Gemma)
// Copyright © 2026 José A. G. Betancourt
// ============================================================

const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions';
const MODEL = 'gemma2-9b-it';

// System prompt: personalidad de la IA
const SYSTEM_PROMPT = `Eres el asistente de Águila Inventario Pro. Eres un gerente de tienda entusiasta y motivador mexicano.
Genera una frase motivacional de máximo 15 palabras para el promotor.
No uses hashtags ni comillas. Usa un tono cálido, profesional y mexicano.
Si se proporciona el nombre del promotor, inclúyelo en la frase.
Si se proporciona la hora del día, adapta el saludo (buenos días, buenas tardes, buenas noches).
Responde SOLO con la frase, sin explicaciones adicionales.`;

exports.handler = async function(event, context) {
  // Solo permitir POST
    if (event.httpMethod !== 'POST') {
        return {
              statusCode: 405,
                    headers: {
                            'Content-Type': 'application/json',
                                    'Access-Control-Allow-Origin': '*',
                                            'Access-Control-Allow-Headers': 'Content-Type',
                                                    'Access-Control-Allow-Methods': 'POST, OPTIONS'
                                                          },
                                                                body: JSON.stringify({ error: 'Método no permitido. Usa POST.' })
                                                                    };
                                                                      }

                                                                        // Manejar preflight CORS
                                                                          if (event.httpMethod === 'OPTIONS') {
                                                                              return {
                                                                                    statusCode: 204,
                                                                                          headers: {
                                                                                                  'Access-Control-Allow-Origin': '*',
                                                                                                          'Access-Control-Allow-Headers': 'Content-Type',
                                                                                                                  'Access-Control-Allow-Methods': 'POST, OPTIONS'
                                                                                                                        },
                                                                                                                              body: ''
                                                                                                                                  };
                                                                                                                                    }
                                                                                                                                    
                                                                                                                                      // Leer la API Key desde variables de entorno de Netlify
                                                                                                                                        const API_KEY = process.env.GEMMA_API_KEY;
                                                                                                                                          if (!API_KEY) {
                                                                                                                                              console.error('❌ GEMMA_API_KEY no configurada en Netlify Environment Variables');
                                                                                                                                                  return {
                                                                                                                                                        statusCode: 500,
                                                                                                                                                              headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                    body: JSON.stringify({ error: 'API Key no configurada en el servidor.' })
                                                                                                                                                                        };
                                                                                                                                                                          }
                                                                                                                                                                          
                                                                                                                                                                            try {
                                                                                                                                                                                // Parsear el body del request
                                                                                                                                                                                    const requestBody = JSON.parse(event.body || '{}');
                                                                                                                                                                                        const { userName, hourOfDay, dayOfWeek, date, weather, city } = requestBody;
                                                                                                                                                                                        
                                                                                                                                                                                            // Sanitizar entradas (Anti-Prompt Injection)
                                                                                                                                                                                                const safeName = sanitize(userName || 'Campeón');
                                                                                                                                                                                                    const safeHour = typeof hourOfDay === 'number' ? hourOfDay : new Date().getHours();
                                                                                                                                                                                                    
                                                                                                                                                                                                        // Determinar saludo por hora
                                                                                                                                                                                                            let timeGreeting = 'Buenos días';
                                                                                                                                                                                                                if (safeHour >= 12 && safeHour < 18) timeGreeting = 'Buenas tardes';
                                                                                                                                                                                                                    else if (safeHour >= 18) timeGreeting = 'Buenas noches';
                                                                                                                                                                                                                    
                                                                                                                                                                                                                        // Construir contexto dinámico para el prompt
                                                                                                                                                                                                                            let userPrompt = `Genera una frase motivacional para ${safeName}. Es ${timeGreeting.toLowerCase()}.`;
                                                                                                                                                                                                                                if (dayOfWeek) userPrompt += ` Hoy es ${sanitize(dayOfWeek)}.`;
                                                                                                                                                                                                                                    if (date) userPrompt += ` Fecha: ${sanitize(date)}.`;
                                                                                                                                                                                                                                        if (weather) userPrompt += ` Clima: ${sanitize(weather)}.`;
                                                                                                                                                                                                                                            if (city) userPrompt += ` Ciudad: ${sanitize(city)}.`;
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                // Llamada a la API de Groq (modelo Gemma)
                                                                                                                                                                                                                                                    const response = await fetch(GROQ_API_URL, {
                                                                                                                                                                                                                                                          method: 'POST',
                                                                                                                                                                                                                                                                headers: {
                                                                                                                                                                                                                                                                        'Authorization': `Bearer ${API_KEY}`,
                                                                                                                                                                                                                                                                                'Content-Type': 'application/json'
                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                            body: JSON.stringify({
                                                                                                                                                                                                                                                                                                    model: MODEL,
                                                                                                                                                                                                                                                                                                            messages: [
                                                                                                                                                                                                                                                                                                                      { role: 'system', content: SYSTEM_PROMPT },
                                                                                                                                                                                                                                                                                                                                { role: 'user', content: userPrompt }
                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                temperature: 0.9,
                                                                                                                                                                                                                                                                                                                                                        max_tokens: 60,
                                                                                                                                                                                                                                                                                                                                                                top_p: 0.95
                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                              if (!response.ok) {
                                                                                                                                                                                                                                                                                                                                                                                    const errorData = await response.json().catch(() => ({}));
                                                                                                                                                                                                                                                                                                                                                                                          console.error('❌ Error Groq API:', response.status, JSON.stringify(errorData));
                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                        statusCode: response.status,
                                                                                                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                  error: `Error de la IA (${response.status})`,
                                                                                                                                                                                                                                                                                                                                                                                                                                            details: errorData.error?.message || 'Error desconocido de Groq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const data = await response.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      let phrase = data.choices?.[0]?.message?.content?.trim() || '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Control de longitud: máximo 15 palabras
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (phrase) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const words = phrase.split(' ');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (words.length > 15) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  phrase = words.slice(0, 15).join(' ');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Limpiar comillas y hashtags
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    phrase = phrase.replace(/["#]/g, '').trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!phrase) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          statusCode: 200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    phrase: `¡${safeName}, hoy es tu día para brillar! Adelante campeón.`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              source: 'fallback'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          statusCode: 200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body: JSON.stringify({ phrase, source: 'groq-gemma' })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('🛡️ Error en generate-phrase:', error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          statusCode: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              error: 'Error interno del servidor',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      details: error.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Utilidad: Sanitización de entradas (Anti-Prompt Injection)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function sanitize(text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!text) return '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return String(text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .replace(/[<>{}[\]\\\/]/g, '')  // Eliminar caracteres peligrosos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .replace(/\n|\r/g, ' ')         // Eliminar saltos de línea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .substring(0, 100)              // Limitar longitud
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
